# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Zynq_Book/Lab_3/Lab_3.srcs/sources_1/bd/Lab_3/ip/Lab_3_xbar_1/Lab_3_xbar_1.xci
# IP: The module: 'Lab_3_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/Lab_3/Lab_3.srcs/sources_1/bd/Lab_3/ip/Lab_3_xbar_1/Lab_3_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_3_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Zynq_Book/Lab_3/Lab_3.srcs/sources_1/bd/Lab_3/ip/Lab_3_xbar_1/Lab_3_xbar_1.xci
# IP: The module: 'Lab_3_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/Lab_3/Lab_3.srcs/sources_1/bd/Lab_3/ip/Lab_3_xbar_1/Lab_3_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_3_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
