# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Lab_3/Lab_3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3 || ORIG_REF_NAME==Lab_3} -quiet] -quiet

# IP: bd/Lab_3/ip/Lab_3_processing_system7_0_0/Lab_3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3_processing_system7_0_0 || ORIG_REF_NAME==Lab_3_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab_3/ip/Lab_3_axi_gpio_0_1/Lab_3_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3_axi_gpio_0_1 || ORIG_REF_NAME==Lab_3_axi_gpio_0_1} -quiet] -quiet

# IP: bd/Lab_3/ip/Lab_3_axi_gpio_1_1/Lab_3_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3_axi_gpio_1_1 || ORIG_REF_NAME==Lab_3_axi_gpio_1_1} -quiet] -quiet

# IP: bd/Lab_3/ip/Lab_3_axi_timer_0_0/Lab_3_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3_axi_timer_0_0 || ORIG_REF_NAME==Lab_3_axi_timer_0_0} -quiet] -quiet

# IP: bd/Lab_3/ip/Lab_3_xlconcat_0_0/Lab_3_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3_xlconcat_0_0 || ORIG_REF_NAME==Lab_3_xlconcat_0_0} -quiet] -quiet

# IP: bd/Lab_3/ip/Lab_3_xbar_1/Lab_3_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3_xbar_1 || ORIG_REF_NAME==Lab_3_xbar_1} -quiet] -quiet

# IP: bd/Lab_3/ip/Lab_3_ps7_0_axi_periph_1/Lab_3_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3_ps7_0_axi_periph_1 || ORIG_REF_NAME==Lab_3_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/Lab_3/ip/Lab_3_rst_ps7_0_100M_1/Lab_3_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3_rst_ps7_0_100M_1 || ORIG_REF_NAME==Lab_3_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/Lab_3/ip/Lab_3_auto_pc_0/Lab_3_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3_auto_pc_0 || ORIG_REF_NAME==Lab_3_auto_pc_0} -quiet] -quiet

# IP: bd/Lab_3/ip/Lab_3_axi_gpio_2_0/Lab_3_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3_axi_gpio_2_0 || ORIG_REF_NAME==Lab_3_axi_gpio_2_0} -quiet] -quiet

# XDC: bd/Lab_3/Lab_3_ooc.xdc
